### ekf config file ###
ekf_filter_node:
    ros__parameters:

        use_sim_time: true
        
        # The frequency, in Hz, at which the filter will output a position estimate.
        frequency: 30.0

        # The period, in seconds, after which we consider a sensor to have timed out.
        sensor_timeout: 0.1

        # Use this to switch to a 2D mode for planar environments.
        two_d_mode: true

        # Time offset for the transform.
        transform_time_offset: 0.0

        # Timeout for the transform listener.
        transform_timeout: 0.0

        # Print diagnostics.
        print_diagnostics: true

        # Debugging settings (for advanced use).
        debug: false

        # Path for debug output file.
        debug_out_file: /path/to/debug/file.txt

        # Whether to publish the transform over tf.
        publish_tf: true

        # Whether to publish acceleration state.
        publish_acceleration: false

        # Reset filter on time jump.
        reset_on_time_jump: true

        # Coordinate frames configuration.
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        # Define input odometry sensor topic.
        odom0: /smart_car/wheel/odom

        # Configuration for odometry input sensor.
        odom0_config: [true, true, true,   # Enable x, y, z positions
                       false, false, true, # Disable roll, pitch, and yaw; enable yaw angle
                       false, false, false, # Disable velocities (vx, vy, vz)
                       false, false, false, # Disable angular velocities (vroll, vpitch, vyaw)
                       false, false, false]

        # Size of subscription queue for odometry input.
        odom0_queue_size: 2

        # Disable Nagle's algorithm for large messages.
        odom0_nodelay: false

        # Use differential mode for odometry input.
        odom0_differential: true

        # Use relative mode for odometry input.
        odom0_relative: false

        # Rejection thresholds for pose and twist data.
        odom0_pose_rejection_threshold: 10.0
        odom0_twist_rejection_threshold: 5.0

        # Configuration for IMU input sensor.
        imu0: imu_data
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      true,  true,  true,
                      true,  true,  true]

        # Advanced IMU settings.
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true
        imu0_queue_size: 7
        imu0_pose_rejection_threshold: 0.8
        imu0_twist_rejection_threshold: 0.8
        imu0_linear_acceleration_rejection_threshold: 0.8

        # Remove gravitational acceleration if IMU does not.
        imu0_remove_gravitational_acceleration: true

        # Use control input during prediction.
        use_control: false

        # Whether input is a Twist or TwistStamped message.
        stamped_control: false

        # Control timeout.
        control_timeout: 0.2

        # Controlled velocities (vx, vy, vz, vroll, vpitch, vyaw).
        control_config: [true, false, false, false, false, true]

        # Acceleration and deceleration limits.
        acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.4]
        deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 4.5]

        # Acceleration and deceleration gains.
        acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
        deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

        # Process noise covariance matrix.
        process_noise_covariance: [0.1,   0.1,    0.1,    0.0,    0.0,    0.0,    0.05,    0.05,    0.05,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.1,   0.1,    0.0,    0.0,    0.0,    0.05,    0.05,    0.05,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.1,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.1,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.1,    0.0,    0.05,    0.05,    0.05,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.1,    0.05,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0]

        # Initial estimate covariance matrix (small non-zero values to avoid NaN).
        initial_estimate_covariance: [1e-6,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    1e-6,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    1e-6,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    1e-6,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    1e-6,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    1e-6,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-6,   0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0]
