ackermann_steering_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  joint_names:
    - "front_left_wheel_steer_joint"
    - "front_right_wheel_steer_joint"
    - "back_left_wheel_joint"
    - "back_right_wheel_joint"
  cmd_vel_timeout: 0.5
  wheelbase: 0.3
  trackwidth: 0.2
  steer_ratio: 1.0
